version: '3'
services:
  ckip-service:
    image: jyhsu2000/ckip-service
    build: .
    restart: unless-stopped
    environment:
      - PYTHONIOENCODING=utf-8
    ports:
      - 127.0.0.1:5005:5005
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/app/data:ro
