version: '3'
services:
  ckip:
    container_name: ckip-service
    build: .
    restart: always
    environment:
      - PYTHONIOENCODING=utf-8
    ports:
      - 127.0.0.1:5005:5005
    volumes:
      - ./:/usr/local/src/CKIPTagger
      - /etc/localtime:/etc/localtime:ro
      - ./data:/usr/local/src/CKIPTagger/data:ro
